#Varaha Krishna Arangi

#Below package is used in creating pie charts

In [1]:
#Installing Plotrix package
install.packages("plotrix")

  There is a binary version available but the source version is later:
        binary source needs_compilation
plotrix  3.8-1  3.8-2             FALSE

installing the source package 'plotrix'

In [2]:
# Importing necessary packages of R
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(plotrix)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

Attaching package: 'reshape2'

The following object is masked from 'package:tidyr':

    smiths

#read.csv file is reading the file with arguments.

In [3]:
#Reading and Copying CSV file into Variable variabledt and printing it.
variabledt <- read.csv("C:\\Users\\16823\\Desktop\\R\\CSE5334_A1_002\\dataset_R.csv", header=T,)
print(variabledt)

     Loan_ID Gender Married Dependents    Education Self_Employed
1   LP001002   Male      No          0     Graduate            No
2   LP001003   Male     Yes          1     Graduate            No
3   LP001005   Male     Yes          0     Graduate           Yes
4   LP001006   Male     Yes          0 Not Graduate            No
5   LP001008   Male      No          0     Graduate            No
6   LP001011   Male     Yes          2     Graduate           Yes
7   LP001013   Male     Yes          0 Not Graduate            No
8   LP001014   Male     Yes         3+     Graduate            No
9   LP001018   Male     Yes          2     Graduate            No
10  LP001020   Male     Yes          1     Graduate            No
11  LP001024   Male     Yes          2     Graduate            No
12  LP001027   Male     Yes          2     Graduate
13  LP001028   Male     Yes          2     Graduate            No
14  LP001029   Male      No          0     Graduate            No
15  LP001030   Male     Yes          2     Graduate            No
16  LP001032   Male      No          0     Graduate            No
17  LP001034   Male      No          1 Not Graduate            No
18  LP001036 Female      No          0     Graduate            No
19  LP001038   Male     Yes          0 Not Graduate            No
20  LP001041   Male     Yes          0     Graduate
21  LP001043   Male     Yes          0 Not Graduate            No
22  LP001046   Male     Yes          1     Graduate            No
23  LP001047   Male     Yes          0 Not Graduate            No
24  LP001050            Yes          2 Not Graduate            No
25  LP001052   Male     Yes          1     Graduate
26  LP001066   Male     Yes          0     Graduate           Yes
27  LP001068   Male     Yes          0     Graduate            No
28  LP001073   Male     Yes          2 Not Graduate            No
29  LP001086   Male      No          0 Not Graduate            No
30  LP001087 Female      No          2     Graduate
31  LP001091   Male     Yes          1     Graduate
32  LP001095   Male      No          0     Graduate            No
33  LP001097   Male      No          1     Graduate           Yes
34  LP001098   Male     Yes          0     Graduate            No
35  LP001100   Male      No         3+     Graduate            No
36  LP001106   Male     Yes          0     Graduate            No
37  LP001109   Male     Yes          0     Graduate            No
38  LP001112 Female     Yes          0     Graduate            No
39  LP001114   Male      No          0     Graduate            No
40  LP001116   Male      No          0 Not Graduate            No
41  LP001119   Male      No          0     Graduate            No
42  LP001120   Male      No          0     Graduate            No
43  LP001123   Male     Yes          0     Graduate            No
44  LP001131   Male     Yes          0     Graduate            No
45  LP001136   Male     Yes          0 Not Graduate           Yes
46  LP001137 Female      No          0     Graduate            No
47  LP001138   Male     Yes          1     Graduate            No
48  LP001144   Male     Yes          0     Graduate            No
49  LP001146 Female     Yes          0     Graduate            No
50  LP001151 Female      No          0     Graduate            No
51  LP001155 Female     Yes          0 Not Graduate            No
52  LP001157 Female      No          0     Graduate            No
53  LP001164 Female      No          0     Graduate            No
54  LP001179   Male     Yes          2     Graduate            No
55  LP001186 Female     Yes          1     Graduate           Yes
56  LP001194   Male     Yes          2     Graduate            No
57  LP001195   Male     Yes          0     Graduate            No
58  LP001197   Male     Yes          0     Graduate            No
59  LP001198   Male     Yes          1     Graduate            No
60  LP001199   Male     Yes          2 Not Graduate            No
61  LP001205   Male     Yes          0     Graduate            No
62  LP001206   Male     Yes         3+     Graduate            No
63  LP001207   Male     Yes          0 Not Graduate           Yes
64  LP001213   Male     Yes          1     Graduate            No
65  LP001222 Female      No          0     Graduate            No
66  LP001225   Male     Yes          0     Graduate            No
67  LP001228   Male      No          0 Not Graduate            No
68  LP001233   Male     Yes          1     Graduate            No
69  LP001238   Male     Yes         3+ Not Graduate           Yes
70  LP001241 Female      No          0     Graduate            No
71  LP001243   Male     Yes          0     Graduate            No
72  LP001245   Male     Yes          2 Not Graduate           Yes
73  LP001248   Male      No          0     Graduate            No
74  LP001250   Male     Yes         3+ Not Graduate            No
75  LP001253   Male     Yes         3+     Graduate           Yes
76  LP001255   Male      No          0     Graduate            No
77  LP001256   Male      No          0     Graduate            No
78  LP001259   Male     Yes          1     Graduate           Yes
79  LP001263   Male     Yes         3+     Graduate            No
80  LP001264   Male     Yes         3+ Not Graduate           Yes
81  LP001265 Female      No          0     Graduate            No
82  LP001266   Male     Yes          1     Graduate           Yes
83  LP001267 Female     Yes          2     Graduate            No
84  LP001273   Male     Yes          0     Graduate            No
85  LP001275   Male     Yes          1     Graduate            No
86  LP001279   Male      No          0     Graduate            No
87  LP001280   Male     Yes          2 Not Graduate            No
88  LP001282   Male     Yes          0     Graduate            No
89  LP001289   Male      No          0     Graduate            No
90  LP001310   Male     Yes          0     Graduate            No
91  LP001316   Male     Yes          0     Graduate            No
92  LP001318   Male     Yes          2     Graduate            No
93  LP001319   Male     Yes          2 Not Graduate            No
94  LP001322   Male      No          0     Graduate            No
95  LP001325   Male      No          0 Not Graduate            No
96  LP001326   Male      No          0     Graduate
97  LP001327 Female     Yes          0     Graduate            No
98  LP001333   Male     Yes          0     Graduate            No
99  LP001334   Male     Yes          0 Not Graduate            No
100 LP001343   Male     Yes          0     Graduate            No
101 LP001345   Male     Yes          2 Not Graduate            No
102 LP001349   Male      No          0     Graduate            No
103 LP001350   Male     Yes                Graduate            No
104 LP001356   Male     Yes          0     Graduate            No
105 LP001357   Male                        Graduate            No
106 LP001367   Male     Yes          1     Graduate            No
107 LP001369   Male     Yes          2     Graduate            No
108 LP001370   Male      No          0 Not Graduate
109 LP001379   Male     Yes          2     Graduate            No
110 LP001384   Male     Yes         3+ Not Graduate            No
111 LP001385   Male      No          0     Graduate            No
112 LP001387 Female     Yes          0     Graduate
113 LP001391   Male     Yes          0 Not Graduate            No
114 LP001392 Female      No          1     Graduate           Yes
115 LP001398   Male      No          0     Graduate
116 LP001401   Male     Yes          1     Graduate            No
117 LP001404 Female     Yes          0     Graduate            No
118 LP001405   Male     Yes          1     Graduate            No
119 LP001421   Male     Yes          0     Graduate            No
120 LP001422 Female      No          0     Graduate            No
121 LP001426   Male     Yes                Graduate            No
122 LP001430 Female      No          0     Graduate            No
123 LP001431 Female      No          0     Graduate            No
124 LP001432   Male     Yes          2     Graduate            No
125 LP001439   Male     Yes          0 Not Graduate            No
126 LP001443 Female      No          0     Graduate            No
127 LP001448            Yes         3+     Graduate            No
128 LP001449   Male      No          0     Graduate            No
129 LP001451   Male     Yes          1     Graduate           Yes
130 LP001465   Male     Yes          0     Graduate            No
131 LP001469   Male      No          0     Graduate           Yes
132 LP001473   Male      No          0     Graduate            No
133 LP001478   Male      No          0     Graduate            No
134 LP001482   Male     Yes          0     Graduate           Yes
135 LP001487   Male      No          0     Graduate            No
136 LP001488   Male     Yes         3+     Graduate            No
137 LP001489 Female     Yes          0     Graduate            No
138 LP001491   Male     Yes          2     Graduate           Yes
139 LP001492   Male      No          0     Graduate            No
140 LP001493   Male     Yes          2 Not Graduate            No
141 LP001497   Male     Yes          2     Graduate            No
142 LP001498   Male      No          0     Graduate            No
143 LP001504   Male      No          0     Graduate           Yes
144 LP001507   Male     Yes          0     Graduate            No
145 LP001508   Male     Yes          2     Graduate            No
146 LP001514 Female     Yes          0     Graduate            No
147 LP001516 Female     Yes          2     Graduate            No
148 LP001518   Male     Yes          1     Graduate            No
149 LP001519 Female      No          0     Graduate            No
150 LP001520   Male     Yes          0     Graduate            No
151 LP001528   Male      No          0     Graduate            No
152 LP001529   Male     Yes          0     Graduate           Yes
153 LP001531   Male      No          0     Graduate            No
154 LP001532   Male     Yes          2 Not Graduate            No
155 LP001535   Male      No          0     Graduate            No
156 LP001536   Male     Yes         3+     Graduate            No
157 LP001541   Male     Yes          1     Graduate            No
158 LP001543   Male     Yes          1     Graduate            No
159 LP001546   Male      No          0     Graduate
160 LP001552   Male     Yes          0     Graduate            No
161 LP001560   Male     Yes          0 Not Graduate            No
162 LP001562   Male     Yes          0     Graduate            No
163 LP001565   Male     Yes          1     Graduate            No
164 LP001570   Male     Yes          2     Graduate            No
165 LP001572   Male     Yes          0     Graduate            No
166 LP001574   Male     Yes          0     Graduate            No
167 LP001577 Female     Yes          0     Graduate            No
168 LP001578   Male     Yes          0     Graduate            No
169 LP001579   Male      No          0     Graduate            No
170 LP001580   Male     Yes          2     Graduate            No
171 LP001581   Male     Yes          0 Not Graduate
172 LP001585            Yes         3+     Graduate            No
173 LP001586   Male     Yes         3+ Not Graduate            No
174 LP001594   Male     Yes          0     Graduate            No
175 LP001603   Male     Yes          0 Not Graduate           Yes
176 LP001606   Male     Yes          0     Graduate            No
177 LP001608   Male     Yes          2     Graduate            No
178 LP001610   Male     Yes         3+     Graduate            No
179 LP001616   Male     Yes          1     Graduate            No
180 LP001630   Male      No          0 Not Graduate            No
181 LP001633   Male     Yes          1     Graduate            No
182 LP001634   Male      No          0     Graduate            No
183 LP001636   Male     Yes          0     Graduate            No
184 LP001637   Male     Yes          1     Graduate            No
185 LP001639 Female     Yes          0     Graduate            No
186 LP001640   Male     Yes          0     Graduate           Yes
187 LP001641   Male     Yes          1     Graduate           Yes
188 LP001643   Male     Yes          0     Graduate            No
189 LP001644            Yes          0     Graduate           Yes
190 LP001647   Male     Yes          0     Graduate            No
191 LP001653   Male      No          0 Not Graduate            No
192 LP001656   Male      No          0     Graduate            No
193 LP001657   Male     Yes          0 Not Graduate            No
194 LP001658   Male      No          0     Graduate            No
195 LP001664   Male      No          0     Graduate            No
196 LP001665   Male     Yes          1     Graduate            No
197 LP001666   Male      No          0     Graduate            No
198 LP001669 Female      No          0 Not Graduate            No
199 LP001671 Female     Yes          0     Graduate            No
200 LP001673   Male      No          0     Graduate           Yes
201 LP001674   Male     Yes          1 Not Graduate            No
202 LP001677   Male      No          2     Graduate            No
203 LP001682   Male     Yes         3+ Not Graduate            No
204 LP001688   Male     Yes          1 Not Graduate            No
205 LP001691   Male     Yes          2 Not Graduate            No
206 LP001692 Female      No          0 Not Graduate            No
207 LP001693 Female      No          0     Graduate            No
208 LP001698   Male      No          0 Not Graduate            No
209 LP001699   Male      No          0     Graduate            No
210 LP001702   Male      No          0     Graduate            No
211 LP001708 Female      No          0     Graduate            No
212 LP001711   Male     Yes         3+     Graduate            No
213 LP001713   Male     Yes          1     Graduate           Yes
214 LP001715   Male     Yes         3+ Not Graduate           Yes
215 LP001716   Male     Yes          0     Graduate            No
216 LP001720   Male     Yes         3+ Not Graduate            No
217 LP001722   Male     Yes          0     Graduate            No
218 LP001726   Male     Yes          0     Graduate            No
219 LP001732   Male     Yes          2     Graduate
220 LP001734 Female     Yes          2     Graduate            No
221 LP001736   Male     Yes          0     Graduate            No
222 LP001743   Male     Yes          2     Graduate            No
223 LP001744   Male      No          0     Graduate            No
224 LP001749   Male     Yes          0     Graduate            No
225 LP001750   Male     Yes          0     Graduate            No
226 LP001751   Male     Yes          0     Graduate            No
227 LP001754   Male     Yes            Not Graduate           Yes
228 LP001758   Male     Yes          2     Graduate            No
229 LP001760   Male                        Graduate            No
230 LP001761   Male      No          0     Graduate           Yes
231 LP001765   Male     Yes          1     Graduate            No
232 LP001768   Male     Yes          0     Graduate
233 LP001770   Male      No          0 Not Graduate            No
234 LP001776 Female      No          0     Graduate            No
235 LP001778   Male     Yes          1     Graduate            No
236 LP001784   Male     Yes          1     Graduate            No
237 LP001786   Male     Yes          0     Graduate
238 LP001788 Female      No          0     Graduate           Yes
239 LP001790 Female      No          1     Graduate            No
240 LP001792   Male     Yes          1     Graduate            No
241 LP001798   Male     Yes          2     Graduate            No
242 LP001800   Male     Yes          1 Not Graduate            No
243 LP001806   Male      No          0     Graduate            No
244 LP001807   Male     Yes          2     Graduate           Yes
245 LP001811   Male     Yes          0 Not Graduate            No
246 LP001813   Male      No          0     Graduate           Yes
247 LP001814   Male     Yes          2     Graduate            No
248 LP001819   Male     Yes          1 Not Graduate            No
249 LP001824   Male     Yes          1     Graduate            No
250 LP001825   Male     Yes          0     Graduate            No
251 LP001835   Male     Yes          0 Not Graduate            No
252 LP001836 Female      No          2     Graduate            No
253 LP001841   Male      No          0 Not Graduate           Yes
254 LP001843   Male     Yes          1 Not Graduate            No
255 LP001844   Male      No          0     Graduate           Yes
256 LP001846 Female      No         3+     Graduate            No
257 LP001849   Male      No          0 Not Graduate            No
258 LP001854   Male     Yes         3+     Graduate            No
259 LP001859   Male     Yes          0     Graduate            No
260 LP001864   Male     Yes         3+ Not Graduate            No
261 LP001865   Male     Yes          1     Graduate            No
262 LP001868   Male      No          0     Graduate            No
263 LP001870 Female      No          1     Graduate            No
264 LP001871 Female      No          0     Graduate            No
265 LP001872   Male      No          0     Graduate           Yes
266 LP001875   Male      No          0     Graduate            No
267 LP001877   Male     Yes          2     Graduate            No
268 LP001882   Male     Yes         3+     Graduate            No
269 LP001883 Female      No          0     Graduate
270 LP001884 Female      No          1     Graduate            No
271 LP001888 Female      No          0     Graduate            No
272 LP001891   Male     Yes          0     Graduate            No
273 LP001892   Male      No          0     Graduate            No
274 LP001894   Male     Yes          0     Graduate            No
275 LP001896   Male     Yes          2     Graduate            No
276 LP001900   Male     Yes          1     Graduate            No
277 LP001903   Male     Yes          0     Graduate            No
278 LP001904   Male     Yes          0     Graduate            No
279 LP001907   Male     Yes          0     Graduate            No
280 LP001908 Female     Yes          0 Not Graduate            No
281 LP001910   Male      No          1 Not Graduate           Yes
282 LP001914   Male     Yes          0     Graduate            No
283 LP001915   Male     Yes          2     Graduate            No
284 LP001917 Female      No          0     Graduate            No
285 LP001922   Male     Yes          0     Graduate            No
286 LP001924   Male      No          0     Graduate            No
287 LP001925 Female      No          0     Graduate           Yes
288 LP001926   Male     Yes          0     Graduate            No
289 LP001931 Female      No          0     Graduate            No
290 LP001935   Male      No          0     Graduate            No
291 LP001936   Male     Yes          0     Graduate            No
292 LP001938   Male     Yes          2     Graduate            No
293 LP001940   Male     Yes          2     Graduate            No
294 LP001945 Female      No                Graduate            No
295 LP001947   Male     Yes          0     Graduate            No
296 LP001949   Male     Yes         3+     Graduate
297 LP001953   Male     Yes          1     Graduate            No
298 LP001954 Female     Yes          1     Graduate            No
299 LP001955 Female      No          0     Graduate            No
300 LP001963   Male     Yes          1     Graduate            No
301 LP001964   Male     Yes          0 Not Graduate            No
302 LP001972   Male     Yes            Not Graduate            No
303 LP001974 Female      No          0     Graduate            No
304 LP001977   Male     Yes          1     Graduate            No
305 LP001978   Male      No          0     Graduate            No

head returns first five rows of the data set.

In [4]:
# Displaying the first 5 rows of the data set using head function.
head(variabledt,5)

  Loan_ID  Gender Married Dependents Education    Self_Employed ApplicantIncome
1 LP001002 Male   No      0          Graduate     No            5849
2 LP001003 Male   Yes     1          Graduate     No            4583
3 LP001005 Male   Yes     0          Graduate     Yes           3000
4 LP001006 Male   Yes     0          Not Graduate No            2583
5 LP001008 Male   No      0          Graduate     No            6000
  CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History Property_Area
1    0               NA        360              1              Urban
2 1508              128        360              1              Rural
3    0               66        360              1              Urban
4 2358              120        360              1              Urban
5    0              141        360              1              Urban
  Loan_Status
1 Y
2 N
3 Y
4 Y
5 Y

In [5]:
#Task 1A

The built-in R function colSums() returns a matrix's or data frame's column sums. It generates a numeric vector with the column sums after computing the sum of each column separately.
Empty values are replaced by NA for easier handling of the data.

In [6]:

variabledt[variabledt == ""] <- NA
colSums(is.na(variabledt))

          Loan_ID            Gender           Married        Dependents
                0                13                 3                15
        Education     Self_Employed   ApplicantIncome CoapplicantIncome
                0                32                 0                 0
       LoanAmount  Loan_Amount_Term    Credit_History     Property_Area
               22                14                50                 0
      Loan_Status
                0

Printing the columns names of the dataset using colnames function in R.

In [7]:
#Task 1-b Print the details of dataframe
print("The class labels are:")
colnames(variabledt)

[1] "The class labels are:"

 [1] "Loan_ID"           "Gender"            "Married"
 [4] "Dependents"        "Education"         "Self_Employed"
 [7] "ApplicantIncome"   "CoapplicantIncome" "LoanAmount"
[10] "Loan_Amount_Term"  "Credit_History"    "Property_Area"
[13] "Loan_Status"

printing the details of the data frame and it's column types using str function in R.

In [8]:

str(variabledt)

'data.frame':	614 obs. of  13 variables:
 $ Loan_ID          : Factor w/ 614 levels "LP001002","LP001003",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ Gender           : Factor w/ 3 levels "","Female","Male": 3 3 3 3 3 3 3 3 3 3 ...
 $ Married          : Factor w/ 3 levels "","No","Yes": 2 3 3 3 2 3 3 3 3 3 ...
 $ Dependents       : Factor w/ 5 levels "","0","1","2",..: 2 3 2 2 2 4 2 5 4 3 ...
 $ Education        : Factor w/ 2 levels "Graduate","Not Graduate": 1 1 1 2 1 1 2 1 1 1 ...
 $ Self_Employed    : Factor w/ 3 levels "","No","Yes": 2 2 3 2 2 3 2 2 2 2 ...
 $ ApplicantIncome  : int  5849 4583 3000 2583 6000 5417 2333 3036 4006 12841 ...
 $ CoapplicantIncome: num  0 1508 0 2358 0 ...
 $ LoanAmount       : int  NA 128 66 120 141 267 95 158 168 349 ...
 $ Loan_Amount_Term : int  360 360 360 360 360 360 360 360 360 360 ...
 $ Credit_History   : int  1 1 1 1 1 1 1 0 1 1 ...
 $ Property_Area    : Factor w/ 3 levels "Rural","Semiurban",..: 3 1 3 3 3 3 3 2 3 2 ...
 $ Loan_Status      : Factor w/ 2 levels "N","Y": 2 1 2 2 2 2 2 1 2 1 ...

we can get count of rows and columns by using  nrow() and ncol()

In [9]:
#Task 1c
cat("\n\nnumber of rows is ",nrow(variabledt)) 
cat("\nnumber of columns is ",ncol(variabledt))

number of rows is  614
number of columns is  13

we can get details of the dataset by using summary function and then printing it.

In [10]:
#Task 1D
descriptive<-summary(variabledt)
descriptive

     Loan_ID       Gender    Married    Dependents        Education
 LP001002:  1         :  0       :  0       :  0   Graduate    :480
 LP001003:  1   Female:112   No  :213   0   :345   Not Graduate:134
 LP001005:  1   Male  :489   Yes :398   1   :102
 LP001006:  1   NA's  : 13   NA's:  3   2   :101
 LP001008:  1                           3+  : 51
 LP001011:  1                           NA's: 15
 (Other) :608
 Self_Employed ApplicantIncome CoapplicantIncome   LoanAmount
     :  0      Min.   :  150   Min.   :    0     Min.   :  9.0
 No  :500      1st Qu.: 2878   1st Qu.:    0     1st Qu.:100.0
 Yes : 82      Median : 3812   Median : 1188     Median :128.0
 NA's: 32      Mean   : 5403   Mean   : 1621     Mean   :146.4
               3rd Qu.: 5795   3rd Qu.: 2297     3rd Qu.:168.0
               Max.   :81000   Max.   :41667     Max.   :700.0
                                                 NA's   :22
 Loan_Amount_Term Credit_History     Property_Area Loan_Status
 Min.   : 12      Min.   :0.0000   Rural    :179   N:192
 1st Qu.:360      1st Qu.:1.0000   Semiurban:233   Y:422
 Median :360      Median :1.0000   Urban    :202
 Mean   :342      Mean   :0.8422
 3rd Qu.:360      3rd Qu.:1.0000
 Max.   :480      Max.   :1.0000
 NA's   :14       NA's   :50

#Data Pre-processing for R
#References https://www.tutorialspoint.com/r/r_data_frames.htm
#Data Pre-processing on Dependents column by converting 3+values into 4 so that while processing/performing any operation on row it becomes easy.

In [11]:
variabledt$Dependents <- as.character(variabledt$Dependents)
variabledt$Dependents[variabledt$Dependents == "3+"] <- "4"
head(variabledt,10)

   Loan_ID  Gender Married Dependents Education    Self_Employed
1  LP001002 Male   No      0          Graduate     No
2  LP001003 Male   Yes     1          Graduate     No
3  LP001005 Male   Yes     0          Graduate     Yes
4  LP001006 Male   Yes     0          Not Graduate No
5  LP001008 Male   No      0          Graduate     No
6  LP001011 Male   Yes     2          Graduate     Yes
7  LP001013 Male   Yes     0          Not Graduate No
8  LP001014 Male   Yes     4          Graduate     No
9  LP001018 Male   Yes     2          Graduate     No
10 LP001020 Male   Yes     1          Graduate     No
   ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History
1   5849               0              NA        360              1
2   4583            1508             128        360              1
3   3000               0              66        360              1
4   2583            2358             120        360              1
5   6000               0             141        360              1
6   5417            4196             267        360              1
7   2333            1516              95        360              1
8   3036            2504             158        360              0
9   4006            1526             168        360              1
10 12841           10968             349        360              1
   Property_Area Loan_Status
1  Urban         Y
2  Rural         N
3  Urban         Y
4  Urban         Y
5  Urban         Y
6  Urban         Y
7  Urban         Y
8  Semiurban     N
9  Urban         Y
10 Semiurban     N

#In order to get total number of graduates from rural areas we will have to choose columns which can fetch us these values i.e Property area and Education.
#Next step is to filter them with specified columnsi.e Property area and Education.Print i.e Property area and Education. the count of graduates by using summarise function.

In [12]:
#Task 2-a

x = variabledt %>% select(Property_Area,Education) %>% filter(variabledt$Property_Area == "Rural" & Education == "Graduate") %>% summarise(count1 = n())
x

  count1
1 131

In order to get total number of men who did not graduate we will have to choose those corresponding columns which can fetch us these values i.e Gender and Education.
#Next step is to filter them with specified columns i.e Gender and Education.print the count of men who did not graduate by using summarise function.

In [13]:
#Task 2-b

x = variabledt %>% select(Gender,Education) %>% filter(variabledt$Gender == "Male" & Education == "Not Graduate") %>% summarise(count2 = n())
x

  count2
1 113

It displays top 10 rows in who are graduates and male using subset function

In [14]:
#Task 2-c
men_grad = subset(variabledt,variabledt$Education=="Graduate" & variabledt$Gender=="Male")
result = men_grad
result = result[order(-result$ApplicantIncome),]
head(result,10)

    Loan_ID  Gender Married Dependents Education Self_Employed ApplicantIncome
410 LP002317 Male   Yes     4          Graduate  No            81000
334 LP002101 Male   Yes     0          Graduate  NA            63337
156 LP001536 Male   Yes     4          Graduate  No            39999
186 LP001640 Male   Yes     0          Graduate  Yes           39147
444 LP002422 Male   No      1          Graduate  No            37719
184 LP001637 Male   Yes     1          Graduate  No            33846
507 LP002624 Male   Yes     0          Graduate  No            20833
285 LP001922 Male   Yes     0          Graduate  No            20667
309 LP001996 Male   No      0          Graduate  No            20233
131 LP001469 Male   No      0          Graduate  Yes           20166
    CoapplicantIncome LoanAmount Loan_Amount_Term Credit_History Property_Area
410    0              360        360               0             Rural
334    0              490        180               1             Urban
156    0              600        180               0             Semiurban
186 4750              120        360               1             Semiurban
444    0              152        360               1             Semiurban
184    0              260        360               1             Semiurban
507 6667              480        360              NA             Urban
285    0               NA        360               1             Rural
309    0              480        360               1             Rural
131    0              650        480              NA             Urban
    Loan_Status
410 N
334 Y
156 Y
186 Y
444 Y
184 N
507 Y
285 N
309 N
131 Y

#In order to get total number of self-employed male applicants from urban area we will have to choose columns which can fetch us these values i.e Gender,Property_Area,Self_Employed
Next step is to filter them with specified columnsi.e Gender,Property_Area and Self_Employed.Print i.e Property area and self_employee.

In [15]:
# Task 2-d: Find the number of self-employed male applicants from urban area


x = variabledt%>% select(Gender,Property_Area,Self_Employed) %>% filter(variabledt$Gender == "Male" & Property_Area == "Urban" & Self_Employed == "Yes") %>% summarise(count3 = n())
x

  count3
1 19

ggplot function usage To determine the number of each kind, I mapped married to the x axis and count to the y axis. I have used position function as dodge so that bar plotting is not over lapped.

In [16]:
# Task 3-a Make a plot where married applicants are granted loans

       aes(x = Married, 
           fill = Loan_Status)) + 
  geom_bar(position = "dodge")

ERROR: Error in parse(text = x, srcfile = src): <text>:4:31: unexpected ')'
3:        aes(x = Married,
4:            fill = Loan_Status))
                                 ^

I used the built-in piechart function to display the pie chart with the property area, and to calculate the percentage for each component, we categorized the data and calculated the count, which we subsequently divided by the total rows in the data set.

In [ ]:
# Task 3-b Create a pie chart for Property_area and display percentages in legend respectively

data1 = as.data.frame(table(variabledt$Property_Area, dnn = list("Area")), responseName = "freq")
data1

piepercent<- round(100*data1$freq/sum(data1$freq), 1)

pie3D(data1$freq, labels = data1$Area , explode = 0.09, main = "Pie Chart")
legend("topright", legend = piepercent, cex = 1,
       fill = rainbow(length(table(variabledt$Property_Area))))


To get an interesting pattern we have tried to implement the bar plot using ggplot function. We have plotted a graph with Gender, applicant income and Gender, Property_Area colunms.

We can clearly see that Male applicants have higher Applicant income compared to Female or NA i.e why they were granted higher loan amount compared to others.
We have used the position function as dodge so that bar plotting is not overlapped.

In [ ]:

# Task 4: Insights from the data (20 points)
#Find out 'interesting' information from the dataset. Give two insights and Create a visualization for each of the insights. Explain in a few lines your reasoning.

ggplot(variabledt, 
       aes(x = Gender, 
           fill = ApplicantIncome)) + 
  geom_bar(position = "dodge")


We can clearly see from the below data that males have more property area in all three categories of rural, urban, and semi-urban areas compared to females and hence we can conclude that gents have more property area.
Secondly, we can say that females in urban have more property areas compared to others i.e., NA in rural areas which is exactly opposite of others i.e. NA in rural and Urban areas.

In [ ]:

ggplot(variabledt, 
       aes(x = Gender, 
           fill = Property_Area)) + 
  geom_bar(position = "dodge")

References

https://r4stats.com/examples/graphics-ggplot2/ -ggplot in R
https://www.section.io/engineering-education/data-preprocessing-in-r/ - Data preprocessing in R